### PR TITLE
[13.0][ADD] sale_coupon_order_pending_commercial_partner: New module

### PR DESCRIPTION
**Pull request by chienandalu**
Depends on:

- [x] #105 
- [x] #110 

cc @TecnativaTT41520

### CODE REVIEW

**Comment by chienandalu** [comment]
please unstale

**Comment by pedrobaeza** [comment]
@chienandalu can you rebase to check it if not red?

**Comment by chienandalu** [comment]
> @chienandalu can you rebase to check it if not red?

Rebased and green

**Review by pedrobaeza — APPROVED** [review]
Although the work has been transferred to v15, let's merge it being OK for lettings others in this version to use it.

/ocabot merge nobump

**Pull request merged**
