### PR TITLE
[MIG] sale_coupon_criteria_multi_product: Migration to 15.0

### PR DESCRIPTION
**Pull request by carolina-domatix**

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
Thanks @carolina-domatix !

Code and functional review :+1: 

please review @victoralmau 

TT39032

**Comment by pedrobaeza** [comment]
AFAIK, this must be renamed to `coupon_criteria_multi_product`, including all the commit history:

```
git filter-branch --tree-filter 'if [ -d old_module_name ]; then mv old_module_name new_module_name; fi' HEAD
git rebase origin/15.0
```

**Comment by chienandalu** [comment]
> AFAIK, this must be renamed to `coupon_criteria_multi_product`, including all the commit history:

True for this case. And it should depend on `coupon` indeed (only the test would resent)

**Review by victoralmau — APPROVED** [review]
Code review OK

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
It should be renamed (with whole history) and handled with the new structure, and there's also a merge commit in the commit history that should go out.

**Comment by chienandalu** [comment]
The thing to do is to split it into two modules as done in https://github.com/OCA/sale-promotion/pull/101/commits/da66de104344391bb1e3990c2f8a5608ca5818d9

**Comment by pedrobaeza** [comment]
@chienandalu can you take care of this?

**Comment by chienandalu** [comment]
Ok, we'll superseed the PR from @carolina-domatix last commit

**Comment by pedrobaeza** [comment]
Superseded by #122

**Pull request closed without merging**
