### PR TITLE
[15.0][MIG] sale_coupon_order_suggestion: Migration to 15.0

### PR DESCRIPTION
**Pull request by chienandalu**
- [x] Depends on #107 

I made a tentative to migrate the widget to OWL but it stumbled upon legacy incompatibilities. A convert it into an ESM module anyway.

cc @Tecnativa TT39006

please review @CarlosRoca13 @stefan-tecnativa

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
I have tried on runboat with a multi-product criteria and a multi-gift reward, and I'm not able to get the suggestion icon

**Comment by chienandalu** [comment]
I just rebased and it seems to work fine with the updated code now

**Review by pedrobaeza — APPROVED** [review]
OK, tested. If you remove the promotion line, then the icon doesn't appear again, but I think that's something that already happens in previous version. Please check anyway.

/ocabot merge nobump

**Pull request merged**
