### PR TITLE
14.0 mig sale coupon order line link

### PR DESCRIPTION
**Pull request by ilyasProgrammer**
Module renamed to sale_coupon_traceability

### CODE REVIEW

**Comment by ilyasProgrammer** [comment]
@chienandalu can you help to figure out Travis issue please?

**Comment by chienandalu** [comment]
I'd say the repo CIs need to be updated. ping @pedrobaeza

**Comment by ilyasProgrammer** [comment]
@pedrobaeza could you check CI configuration please ?

**Comment by francesco-ooops** [comment]
@pedrobaeza what is needed to do?

**Comment by francesco-ooops** [comment]
@ilyasProgrammer can you rebase?

**Comment by ilyasProgrammer** [comment]
> @ilyasProgrammer can you rebase?

it is in actual state

**Comment by pedrobaeza** [comment]
Please take into account #46

**Comment by ilyasProgrammer** [comment]
@pedrobaeza applied. Moved here: https://github.com/OCA/sale-promotion/pull/53

**Pull request closed without merging**
