### PR TITLE
[16.0][MIG] coupon_multi_gift>loyalty_multi_gift: Migration to version 16.0

### PR DESCRIPTION
**Pull request by pilarvargas-tecnativa**
Supersedes: https://github.com/OCA/sale-promotion/pull/162

cc @Tecnativa TT44321

@chienandalu please review

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
@pilarvargas-tecnativa I just added a commit to avoid the bug we have when creating the multi-gift lines. Check it and update relaunch the `sale_loyalty_multi_gift` CI

**Comment by pilarvargas-tecnativa** [comment]
@chienandalu I have incorporated here the test that checks the fix.

**Comment by chienandalu** [comment]
Great :+1:

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
