### PR TITLE
[16.0][ADD] sale_loyalty_industry

### PR DESCRIPTION
**Pull request by santostelmo**
This module allow to restrict the industries in which the sale loyalty program applies.

Note: Moved from sale-workflow https://github.com/OCA/sale-workflow/pull/2859

### CODE REVIEW

**Review by cyrilmanuel — APPROVED** [review]
LGTM

**Comment by cyrilmanuel** [comment]
Hi @pedrobaeza  can you make a review here please ?

**Comment by pedrobaeza** [comment]
I think this module is not needed if you use `loyalty_partner_applicability` (and its sales counterpart `sale_loyalty_partner_applicability`, which is more generic to filter partners by any condition (including the industry), and it's also done at rule level, not program level, which is more inline with the new v16 approach.

imagen

I know yours is more "direct", but it's very limiting and in the end, I think using the generic one will give more versatility to your customer.

**Comment by santostelmo** [comment]
> I think this module is not needed if you use `loyalty_partner_applicability` (and its sales counterpart `sale_loyalty_partner_applicability`, which is more generic to filter partners by any condition (including the industry), and it's also done at rule level, not program level, which is more inline with the new v16 approach.
> 
> imagen
> 
> I know yours is more "direct", but it's very limiting and in the end, I think using the generic one will give more versatility to your customer.

I have tested this module `sale_loyalty_partner_applicability` and indeed it seems to cover the needs. But i'm afraid that this domain is hard for a odoo user to build. It's less user friendly.

**Pull request closed without merging**
