### PR TITLE
[ADD] sale_coupon_order_suggestion: New module

### PR DESCRIPTION
**Pull request by chienandalu**
This module extends the functionality of `sale_coupon_selection_wizard` giving tips of available promotions to the salesman making the sales order.

Whenever an order line meets an applicable multi gift and multi criteria promotionan icon (🎁) will appear at the right end. Click it to open the wizard and apply the more convenient.

image

cc @Tecnativa TT30852

please review @pedrobaeza @carlosdauden @victoralmau

### CODE REVIEW

**Review by victoralmau — COMMENTED** [review]
Everything seems correct, could you add a little test to check the behavior?

**Comment by chienandalu** [comment]
Yes, here and in sale_coupon_selection_wizard I have to do tests. I'm pending from customer comments so I don't have to redo the backend tours very much :slightly_smiling_face:

**Comment by pedrobaeza** [comment]
@chienandalu can you please check Travis?

**Comment by chienandalu** [comment]
Green now

**Review by pedrobaeza — APPROVED** [review]

**Review by carlosdauden — APPROVED** [review]

**Pull request merged**
