### PR TITLE
[15.0-mig-sale] [MIG] sale_coupon_auto_refresh: Migration to 15.0

### PR DESCRIPTION
**Pull request by XanderDeJaegere**
Migrated sale_coupon_auto_refresh from 14 to 15. Came down to changing SavepointCase to TransactionCase in tests, alongside manifest. Test 4 from version 13 stops working. Custom triggers don't get tested anymore. While testing I noticed it called the _compute_auto_refresh_trigger_data too early which means it didn't notice the change on the note trigger. Can be potentially fixed by manually calling the compute function.

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
Hi @XanderDeJaegere thanks for your work. Keep an eye on

- https://github.com/OCA/sale-promotion/pull/73

It's a forward port of features introduced in 13.0 and they should be included in 15.0 as well.

**Comment by pedrobaeza** [comment]
Please include #73

**Comment by pedrobaeza** [comment]
Please include #73

**Comment by XanderDeJaegere** [comment]
I had this originally migrated but took it out when I noticed it being removed in 14.0.

I'll add it back when I have time :+1:

**Comment by pedrobaeza** [comment]
@XanderDeJaegere are you going to include #73 for finishing this and got merged?

**Comment by chienandalu** [comment]
Also #83 should be included

**Comment by pedrobaeza** [comment]
Closing in favor of #102

**Pull request closed without merging**
