### PR TITLE
[ADD] [14.0] sale_fixed_price_order_line_link: New bridge module

### PR DESCRIPTION
**Pull request by HekkiMelody**
New bridge module

First two commits contain minor tweaks to `sale_coupon_reward_fixed_price` and `sale_coupon_domain_product_reward_fixed_price` meant to facilitate the new module.

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Functional ok!

**Review by PicchiSeba — APPROVED** [review]
Code review: LGTM

**Comment by francesco-ooops** [comment]
@pedrobaeza can we merge? thanks!

**Comment by pedrobaeza** [comment]
My feeling is that there are too many glue modules, so your architecture seems a bit rigid that requires all of them, but well, it's up to you.

Merging due to existing reviews:

/ocabot merge nobump

**Comment by francesco-ooops** [comment]
@pedrobaeza our modules have added: 

- discount on sale order line
- fixed price on sale order line

which I feel are quite useful. Then we had to do a ton of modules to make it work with existing ones (order line link, auto_refresh, ...). 

I think OCA should consolidate a single module with all these features which are quite universally applicable - we'll add that to roadmap.

Cheers

**Pull request merged**
