### PR TITLE
[15.0][MIG] sale_coupon_multiple_code_program: Migration to version 15.0

### PR DESCRIPTION
**Pull request by stefan-tecnativa**
cc@Tecnativa TT39650

@chienandalu @CarlosRoca13 please review!

### CODE REVIEW

**Review by CarlosRoca13 — APPROVED** [review]
LGTM :+1:

**Review by chienandalu — APPROVED** [review]

**Comment by pedrobaeza** [comment]
/ocabot migration sale_coupon_multiple_code_program

Shouldn't this be split into 2 modules?

**Comment by chienandalu** [comment]
No, it's exclusive to sales as it does the hack over a sale.order field

**Comment by pedrobaeza** [comment]
The context stuff on `search` of the `coupon.program` may be generic, but OK to not split for theoretical cases. When we need it on PoS, we'll split.

/ocabot merge nobump

**Pull request merged**
