### PR TITLE
[15.0][MIG] sale_coupon_limit: Migration to 15.0

### PR DESCRIPTION
**Pull request by chienandalu**
Follow-up of #96 

- [x] Partially superseeds #33 although adapting it to v15.0 to respect changes attribution
- [x] Additional adaptations
- [x] Depends on #94 
- [x] Promote to stable sale_commercial_partner https://github.com/OCA/sale-workflow/pull/2342
- [x] Split the module in two.

cc @Tecnativa TT38310

please review @pedrobaeza @victoralmau

### CODE REVIEW

**Comment by chienandalu** [comment]
<del>It isn't good. I've lost some history...</del>

It should be ok now

**Review by pedrobaeza — APPROVED** [review]
There's no PNG on `sale_coupon_limit`.

**Comment by chienandalu** [comment]
> There's no PNG on `sale_coupon_limit`.

You mean the icon.png? I see it there

**Comment by pedrobaeza** [comment]
Ah, OK, I was just seeing the migration commit.

**Review by victoralmau — APPROVED** [review]

**Pull request merged**
