### PR TITLE
[NEW] New module sale_coupon_recompute_reward

### PR DESCRIPTION
**Pull request by SilvioC2C**
New module that recomputes sale order reward lines when a sale order line is added, removed or updated

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@chienandalu isn't this similar to `sale_coupon_auto_refresh`?

**Comment by SilvioC2C** [comment]
@pedrobaeza where is the module you mentioned? I couldn't find it before... :sweat_smile:

**Review by chienandalu — COMMENTED** [review]
Looks like it, with a take on performance issues.

**Comment by chienandalu** [comment]
> @pedrobaeza where is the module you mentioned? I couldn't find it before...

No yet published as we developed it in v12. Our plan is to migrate it soon though

**Comment by pedrobaeza** [comment]
David, can you share the code? I think we didn't do the pull request, as the repo was not available.

**Comment by chienandalu** [comment]
Here it is https://github.com/OCA/sale-promotion/pull/11

**Comment by SilvioC2C** [comment]
@chienandalu maybe I could propose a few changes to the v13 module (apply the logic on `sale.order.line` instead of `sale.order`, check only specific fields for performances), and then migrate it all to v14. What do you think?

**Comment by SilvioC2C** [comment]
@chienandalu I opened a new PR here: https://github.com/Tecnativa/sale-promotion/pull/1
Please note that I wasn't able to run the tests at the moment, so feel free to test the updates and come back to me if anything goes wrong :sweat_smile:

**Comment by SilvioC2C** [comment]
@chienandalu I migrated `sale_coupon_auto_refresh` to v14 in #14, could you please take a look at it?

**Comment by pedrobaeza** [comment]
He's on holidays this week, so until next one, he won't be able to review it.

**Comment by SilvioC2C** [comment]
> He's on holidays this week, so until next one, he won't be able to review it.

Oh cool, good for him! :ocean: :palm_tree: :sunglasses:

**Pull request closed without merging**
