### PR TITLE
[14.0][MIG] coupon_limit,sale_coupon_limit

### PR DESCRIPTION
**Pull request by HekkiMelody**
Backport from v15 to maintain the improvements and the module split.

Previous v14 migration effort: https://github.com/OCA/sale-promotion/pull/33/commits
V15 Migration #101

### CODE REVIEW

**Comment by francesco-ooops** [comment]
@chienandalu is it ok to backport 2 modules in a single PR or do you think a single PR per module is needed?

**Comment by pedrobaeza** [comment]
He's on holidays these weeks. I think it can be OK, as it's a special situation where the original module was split into 2.

**Review by francesco-ooops — APPROVED** [review]
Functional review ok!

**Review by Aldeigja — APPROVED** [review]

**Comment by francesco-ooops** [comment]
@pedrobaeza good for merge?

**Comment by pedrobaeza** [comment]
OK based on your reviews:

/ocabot merge nobump

**Pull request merged**
