### PR TITLE
[NEW] sale_coupon_domain_product_discount_in_field: Compatibility 2 modules

### PR DESCRIPTION
**Pull request by GabbasovDinar**
This module allows using 2 modules together: (sale_promotion_discount_in_field and sale_coupon_domain_product_discount). Now we can apply the discount in the field for the order lines matched to the product domain

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Functional review ok!

**Comment by francesco-ooops** [comment]
@chienandalu what do you think of this solution?

**Review by elvise — APPROVED** [review]
LGTM!

**Comment by francesco-ooops** [comment]
@chienandalu @OCA/crm-sales-marketing-maintainers review?

**Review by chienandalu — APPROVED** [review]
:+1: Thanks :)

**Comment by francesco-ooops** [comment]
@pedrobaeza merge pls? :)

**Comment by pedrobaeza** [comment]
Please use as commit message tag `[ADD]` and not `[NEW]`.

https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message

**Comment by francesco-ooops** [comment]
> Please use as commit message tag `[ADD]` and not `[NEW]`.
> 
> https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message

@pedrobaeza couldn't any of these cosmetic checks be automated?

Of course it comes with experience but new devs will most probably repeat these mistakes over and over

**Comment by pedrobaeza** [comment]
I think it's difficult, as how do you determine which kind of commit is it? A linter could exist though about the commit message pattern, but right now we don't any CI step that is able to do this (all of them focus on code content, not the Git part).

**Comment by francesco-ooops** [comment]
@pedrobaeza now good? :)

**Pull request merged**
