### PR TITLE
[16.0][MIG] sale_coupon_criteria_multi_product > sale_loyalty_criteria_multi_product: Migration to version 16.0

### PR DESCRIPTION
**Pull request by pilarvargas-tecnativa**
Supersedes: https://github.com/OCA/sale-promotion/pull/165

Pending from:
- [x] https://github.com/OCA/sale-promotion/pull/184

cc @Tecnativa TT44344

 @chienandalu please review

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
Check tests

**Comment by pilarvargas-tecnativa** [comment]
> Check tests

solved :)

**Review by chienandalu — COMMENTED** [review]
What happenend to the `repeat` column?

image

Also, unrelated error but please check it:

image

**Comment by pilarvargas-tecnativa** [comment]
> What happenend to the `repeat` column?

This functionality is already included in the rules of the program itself, I have indicated it in the context of the base module. I have considered duplicating that functionality.

https://github.com/OCA/sale-promotion/blob/35cbd00cc5ff21ba0a2f0b0873dfa37dc639e335/loyalty_criteria_multi_product/readme/CONTEXT.rst

> Also, unrelated error but please check it:

I'm going to check it

**Comment by pilarvargas-tecnativa** [comment]
ping @chienandalu

**Comment by chienandalu** [comment]
Rebase and drop the deps commit

**Review by chienandalu — APPROVED** [review]
:+1:

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
