### PR TITLE
[15.0][MIG] sale_coupon_auto_refresh: Migration to version 15.0

### PR DESCRIPTION
**Pull request by pilarvargas-tecnativa**
cc @Tecnativa TT37307

@chienandalu @victoralmau please review

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
Thanks :) (Remove WIP from the PR title)

**Comment by pedrobaeza** [comment]
Please rename the migration commit from `[WIP] sale_coupon_auto_refresh: Migration to version 15.0` to `[MIG] sale_coupon_auto_refresh: Migration to version 15.0`

**Comment by pilarvargas-tecnativa** [comment]
> Please rename the migration commit from `[WIP] sale_coupon_auto_refresh: Migration to version 15.0` to `[MIG] sale_coupon_auto_refresh: Migration to version 15.0`

Sorry I didn't realise, it's changed, thanks!

**Review by pedrobaeza — APPROVED** [review]
/ocabot migration sale_coupon_auto_refresh
/ocabot merge nobump

**Pull request merged**
